import { StyleSheet } from "react-native";
import { cardGap, screenWidth, statCardWidth, theme } from "./theme";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.bg,
  },
  appShell: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 10,
  },
  backgroundOrbTop: {
    position: "absolute",
    top: -40,
    right: -30,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: "rgba(91,124,255,0.18)",
  },
  backgroundOrbBottom: {
    position: "absolute",
    bottom: 100,
    left: -60,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: "rgba(138,92,255,0.14)",
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 18,
    gap: 14,
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  eyebrow: {
    color: "#9EB3D9",
    fontSize: 11,
    letterSpacing: 2.4,
    fontWeight: "700",
  },
  headerTitle: {
    color: theme.text,
    fontSize: 20,
    fontWeight: "700",
    marginTop: 6,
    maxWidth: screenWidth - 145,
  },
  alertBell: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.border,
  },
  alertCount: {
    position: "absolute",
    top: -3,
    right: -3,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 4,
    backgroundColor: theme.red,
    alignItems: "center",
    justifyContent: "center",
  },
  alertCountText: {
    color: theme.text,
    fontSize: 10,
    fontWeight: "800",
  },
  avatarRing: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarInner: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#0D1428",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    color: theme.text,
    fontSize: 13,
    fontWeight: "800",
  },
  sceneContainer: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 108,
  },
  sectionStack: {
    gap: 16,
  },
  glassCard: {
    backgroundColor: "rgba(12,18,36,0.88)",
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 28,
    padding: 18,
    shadowColor: "#000",
    shadowOpacity: 0.24,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  gradientCard: {
    borderRadius: 30,
    padding: 20,
    borderWidth: 1,
    borderColor: theme.border,
  },
  cardHeader: {
    marginBottom: 14,
  },
  cardSubtitle: {
    color: "#89A0C7",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  cardTitle: {
    color: theme.text,
    fontSize: 19,
    fontWeight: "700",
    marginTop: 6,
  },
  heroKicker: {
    color: "#B8C7FF",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.7,
    textTransform: "uppercase",
  },
  heroTitle: {
    color: theme.text,
    fontSize: 29,
    lineHeight: 34,
    fontWeight: "800",
    marginTop: 10,
    maxWidth: 290,
  },
  heroBody: {
    color: "#B3C1DA",
    fontSize: 14,
    lineHeight: 22,
    marginTop: 10,
    marginBottom: 18,
  },
  horizontalCards: {
    gap: 12,
    paddingRight: 8,
  },
  trendingCard: {
    width: 250,
    borderRadius: 26,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.border,
  },
  trendingCardTitle: {
    color: theme.text,
    fontSize: 17,
    fontWeight: "800",
    flex: 1,
  },
  cardMetricRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: cardGap,
  },
  statCard: {
    width: statCardWidth,
    backgroundColor: "rgba(17,26,51,0.92)",
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.border,
  },
  statIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  statLabel: {
    color: theme.muted,
    fontSize: 12,
  },
  statValue: {
    color: theme.text,
    fontSize: 24,
    fontWeight: "800",
    marginTop: 4,
  },
  statDetail: {
    color: "#90A6CB",
    fontSize: 12,
    marginTop: 6,
  },
  rowSpread: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  eventDetailTitle: {
    color: theme.text,
    fontSize: 26,
    fontWeight: "800",
  },
  eventHash: {
    color: "#8BBEFF",
    marginTop: 4,
    fontSize: 14,
    fontWeight: "600",
  },
  eventMeta: {
    color: theme.muted,
    fontSize: 13,
    marginTop: 6,
    lineHeight: 19,
  },
  miniMetric: {
    backgroundColor: "rgba(7,11,24,0.72)",
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minWidth: 86,
  },
  miniMetricLabel: {
    color: theme.muted,
    fontSize: 11,
  },
  miniMetricValue: {
    fontSize: 14,
    fontWeight: "700",
    marginTop: 5,
  },
  dataBadge: {
    flex: 1,
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 10,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: theme.border,
  },
  dataBadgeLabel: {
    color: theme.muted,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  dataBadgeValue: {
    fontSize: 15,
    fontWeight: "800",
    marginTop: 6,
  },
  predictionPill: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
  },
  predictionPillCompact: {
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  predictionPillText: {
    fontSize: 12,
    fontWeight: "700",
  },
  predictionPillTextCompact: {
    fontSize: 11,
  },
  buttonShadow: {
    alignSelf: "flex-start",
    shadowColor: theme.blue,
    shadowOpacity: 0.35,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 10 },
  },
  primaryButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 18,
  },
  primaryButtonText: {
    color: theme.text,
    fontSize: 14,
    fontWeight: "700",
  },
  predictionBox: {
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  predictionLabel: {
    color: "#9CB1D4",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1.5,
    fontWeight: "700",
  },
  predictionValue: {
    color: theme.text,
    fontSize: 30,
    fontWeight: "800",
    marginTop: 6,
  },
  predictionCopy: {
    color: "#AAB9D3",
    fontSize: 14,
    lineHeight: 22,
    marginTop: 14,
  },
  predictionIconBubble: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(57,217,138,0.12)",
  },
  kpiRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 14,
  },
  alertBanner: {
    borderRadius: 22,
    padding: 14,
    borderWidth: 1,
    borderColor: theme.border,
    flexDirection: "row",
    gap: 12,
    alignItems: "flex-start",
  },
  alertBannerTitle: {
    fontSize: 14,
    fontWeight: "800",
  },
  alertBannerText: {
    color: "#C1D0E8",
    fontSize: 13,
    marginTop: 4,
    lineHeight: 18,
  },
  heatmapGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  heatCell: {
    width: (screenWidth - 84) / 6,
    height: 32,
    borderRadius: 10,
  },
  heatmapLegend: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
  },
  heatLegendText: {
    color: theme.muted,
    fontSize: 12,
  },
  inputGroup: {
    gap: 8,
  },
  inputLabel: {
    color: "#C6D4EE",
    fontSize: 13,
    fontWeight: "600",
  },
  input: {
    backgroundColor: "rgba(7,11,24,0.75)",
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    color: theme.text,
    fontSize: 14,
  },
  textArea: {
    minHeight: 120,
    textAlignVertical: "top",
  },
  feedbackCard: {
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  errorCard: {
    backgroundColor: "rgba(255,107,122,0.06)",
  },
  feedbackTitle: {
    color: theme.text,
    fontSize: 15,
    fontWeight: "800",
  },
  feedbackBody: {
    color: theme.muted,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 6,
  },
  retryButton: {
    marginTop: 12,
    alignSelf: "flex-start",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: "rgba(91,124,255,0.24)",
  },
  retryButtonText: {
    fontSize: 13,
    fontWeight: "700",
  },
  inlineNotice: {
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  inlineNoticeText: {
    fontSize: 12,
    fontWeight: "700",
  },
  formStack: {
    gap: 14,
    marginTop: 18,
  },
  segmentedControl: {
    flexDirection: "row",
    backgroundColor: "rgba(255,255,255,0.05)",
    padding: 4,
    borderRadius: 18,
  },
  segmentedWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 14,
  },
  segmentButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: "center",
  },
  segmentButtonActive: {
    backgroundColor: "#F8FAFC",
  },
  segmentText: {
    color: "#B1C1DA",
    fontSize: 13,
    fontWeight: "700",
  },
  segmentTextActive: {
    color: "#060B16",
  },
  filterChip: {
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: theme.border,
  },
  filterChipActive: {
    backgroundColor: "rgba(91,124,255,0.18)",
  },
  filterChipText: {
    color: "#C3D2EB",
    fontSize: 12,
    fontWeight: "700",
  },
  filterChipTextActive: {
    color: theme.text,
  },
  chartWrap: {
    marginTop: 4,
  },
  chartGrid: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 26,
    justifyContent: "space-between",
  },
  chartLine: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.07)",
  },
  chartBarsRow: {
    height: 170,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 8,
    paddingTop: 12,
  },
  chartBar: {
    flex: 1,
    borderRadius: 16,
  },
  chartLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
  },
  chartLabel: {
    color: theme.muted,
    fontSize: 10,
    flex: 1,
    textAlign: "center",
  },
  discoveryRow: {
    padding: 14,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: 1,
    borderColor: theme.border,
    marginBottom: 10,
  },
  discoveryTitle: {
    color: theme.text,
    fontSize: 17,
    fontWeight: "800",
  },
  discoveryMeta: {
    color: theme.muted,
    fontSize: 12,
    marginTop: 5,
  },
  discoveryMetrics: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  discoveryTags: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 12,
  },
  alertCard: {
    flexDirection: "row",
    gap: 12,
    padding: 14,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: 1,
    borderColor: theme.border,
    marginBottom: 10,
  },
  alertMarker: {
    width: 6,
    borderRadius: 999,
  },
  alertCardTitle: {
    color: theme.text,
    fontSize: 16,
    fontWeight: "800",
  },
  alertType: {
    fontSize: 13,
    fontWeight: "800",
  },
  alertCardDetail: {
    color: "#C1D0E8",
    fontSize: 13,
    marginTop: 5,
    lineHeight: 18,
  },
  alertCardTime: {
    color: theme.muted,
    fontSize: 12,
    marginTop: 8,
  },
  predictionPanel: {
    backgroundColor: "rgba(10,16,34,0.82)",
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  scoreHuge: {
    color: theme.text,
    fontSize: 44,
    fontWeight: "800",
    marginTop: 6,
  },
  scoreCircle: {
    width: 74,
    height: 74,
    borderRadius: 37,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(91,124,255,0.18)",
    borderWidth: 4,
    borderColor: "rgba(91,124,255,0.42)",
  },
  scoreCircleText: {
    color: theme.text,
    fontSize: 18,
    fontWeight: "800",
  },
  divider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.08)",
    marginVertical: 16,
  },
  podiumRow: {
    gap: 12,
  },
  podiumCard: {
    borderRadius: 28,
    padding: 18,
    borderWidth: 1,
    borderColor: theme.border,
  },
  podiumRank: {
    color: "#E8EFFC",
    fontSize: 13,
    fontWeight: "700",
  },
  podiumName: {
    color: theme.text,
    fontSize: 22,
    fontWeight: "800",
    marginTop: 10,
  },
  podiumBadge: {
    color: theme.muted,
    marginTop: 6,
  },
  podiumPoints: {
    color: theme.text,
    fontSize: 18,
    fontWeight: "800",
    marginTop: 16,
  },
  leaderboardRow: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 22,
    padding: 14,
    marginBottom: 10,
  },
  leaderboardRowTop: {
    backgroundColor: "rgba(91,124,255,0.08)",
  },
  rankBadge: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  rankBadgeText: {
    color: theme.text,
    fontWeight: "800",
  },
  leaderName: {
    color: theme.text,
    fontSize: 16,
    fontWeight: "700",
  },
  leaderNameCompact: {
    fontSize: 15,
  },
  leaderBadge: {
    color: theme.muted,
    fontSize: 12,
    marginTop: 4,
  },
  leaderPoints: {
    color: theme.text,
    fontSize: 14,
    fontWeight: "800",
  },
  profileHeader: {
    flexDirection: "row",
    gap: 14,
    alignItems: "center",
  },
  profileAvatarWrap: {
    width: 68,
    height: 68,
    borderRadius: 34,
    alignItems: "center",
    justifyContent: "center",
  },
  profileAvatarInner: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0D1428",
  },
  profileAvatarText: {
    color: theme.text,
    fontSize: 20,
    fontWeight: "800",
  },
  profileName: {
    color: theme.text,
    fontSize: 28,
    fontWeight: "800",
  },
  profileHandle: {
    color: "#9DC0FF",
    fontSize: 14,
    marginTop: 6,
  },
  profileLevel: {
    color: "#C6D4EE",
    fontSize: 16,
    fontWeight: "700",
    marginTop: 8,
  },
  profileStatsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 18,
    flexWrap: "wrap",
  },
  statChip: {
    backgroundColor: "rgba(255,255,255,0.05)",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 18,
    minWidth: 92,
  },
  statChipLabel: {
    color: theme.muted,
    fontSize: 11,
  },
  statChipValue: {
    color: theme.text,
    fontSize: 16,
    fontWeight: "800",
    marginTop: 5,
  },
  badgeWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  achievementChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: theme.border,
  },
  achievementText: {
    color: theme.text,
    fontSize: 13,
    fontWeight: "600",
  },
  infoTile: {
    flexDirection: "row",
    gap: 12,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 22,
    padding: 14,
    marginBottom: 10,
  },
  infoIconBubble: {
    width: 40,
    height: 40,
    borderRadius: 16,
    backgroundColor: "rgba(62,200,255,0.10)",
    alignItems: "center",
    justifyContent: "center",
  },
  infoTitle: {
    color: theme.text,
    fontSize: 15,
    fontWeight: "700",
  },
  infoBody: {
    color: theme.muted,
    fontSize: 13,
    marginTop: 4,
    lineHeight: 19,
  },
  bottomBarWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 16,
  },
  bottomBar: {
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  tabItem: {
    width: 82,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingVertical: 10,
    borderRadius: 18,
    backgroundColor: "rgba(10,16,34,0.96)",
    borderWidth: 1,
    borderColor: theme.border,
  },
  tabItemActive: {
    backgroundColor: "rgba(91,124,255,0.18)",
  },
  tabLabel: {
    color: theme.muted,
    fontSize: 11,
    fontWeight: "700",
  },
  tabLabelActive: {
    color: theme.text,
  },
});
